[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[[menus.main]]
name = 'Layouts'
weight = 10
  [[menus.main]]
  parent = "Layouts"
  name = 'Home'
  pageRef = '/'
  weight = 1

  [[menus.main]]
  parent = "Layouts"
  name = 'Default'
  pageRef = '/sample'
  weight = 2

  [[menus.main]]
  parent = "Layouts"
  name = 'Blog Archive'
  pageRef = '/blog'
  weight = 3

  [[menus.main]]
  parent = "Layouts"
  name = 'Blog Post'
  pageRef = '/blog/post'
  weight = 4

[[menus.main]]
name = "Content Types"
pageRef = '/content-types'
weight = 11

[[menus.main]]
name = 'Sample Page'
pageRef = '/sample'
weight = 20

[[menus.main]]
name = 'Kitchen Sink'
pageRef = '/foundation'
weight = 30

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 40

[[menus.main]]
parent = "Blog"
name = 'Tags'
pageRef = '/tags'
weight = 50

[[menus.main]]
name = 'Get Started'
pageRef = '/foundation'
weight = 60
[menus.main.params]
      class = 'button'


[[menus.secondary]]
name = 'Hugo'
url = 'https://gohugo.io/'
weight = 10
post = '<i class="fa-solid fa-up-right-from-square"></i>'
[menus.secondary.params]
      target = '_blank'

[[menus.secondary]]
name = 'Foundation'
url = 'https://get.foundation/sites/docs/'
weight = 20
post = '<i class="fa-solid fa-up-right-from-square"></i>'
[menus.secondary.params]
      target = '_blank'